### ISSUE TITLE
What is Topic_ID?

### ISSUE THREAD

**Issue by KrlitosForever** [akeylimepie/telegram-action#1]
Hello, I just saw your repository on the marketplace, but I honestly have quite a few doubts about how to implement it and I would like your help. Where do I get `secrets.token`? Is it what BotFather from Telegram provides? What about `secrets.chat_id`? Is it my Telegram ID? And of course, I have no idea what `topic_id` is. 

Could you give me an example of how to fill in those fields? I would really appreciate it.

Best regards.

**Comment by akeylimepie** [comment]
This repo is just a simple wrapper for [sendMessage method](https://core.telegram.org/bots/api#sendmessage), so you can read more about all parameters in the doc.

Briefly about the parameters from the example:

- token: yes, this is your bot's token from BotFather
- chat_id: ID of the target chat; if you want to send a message to yourself, that's your ID, yes
- message_thread_id: ID of the target thread, usefull for forum supergroups only; if you don't need it — just don't use it, it's an optional parameter

**Comment by KrlitosForever** [comment]
Thank you very much for the information, you are very kind and gentle. Have an excellent day!
